### ISSUE TITLE
`parse_html_custom` looks non-functional

### ISSUE THREAD

**Issue by droundy** [Adonai/html2md#1]
It looks like `parse_html_custom` cannot be made to work, because the `Handle` type used by the `handle` method is private, and the `StructuredPrinter` type also used by `handle` and `after_handle` has no public methods (beyond printing with `Debug`).

Am I correct that the custom parsing is a work in progress?

**Comment by Adonai** [comment]
Try again, with v. 0.2.6

**Comment by mckinney-subgraph** [comment]
Hi, I also encountered this problem. I tried with v0.2.6 but the problem is still there.

**Comment by Adonai** [comment]
@mckinney-subgraph , what issue do you have? What traits/classes are unusable? I'll fix it right away.

**Comment by mckinney-subgraph** [comment]
@Adonai I wasn't able to call the methods of StructuredPrinter (insert_str, etc..) due to them being private when using my own TagHandler.

**Comment by Adonai** [comment]
Try with 0.2.7

**Comment by mckinney-subgraph** [comment]
Thanks @Adonai, 0.2.7 seems to have done the trick :)

**Comment by Adonai** [comment]
Great. I'm closing this, feel free to comment if you need to reopen it.
